# Wallust generated Vicinae theme

[meta]
version = 1
name = "Wallust"
description = "Dynamic colors from wallpaper"
variant = "dark"

[colors.core]
background = "#242628"
foreground = "#DADCDC"
secondary_background = "#4A4C4E"
border = "#878989"
accent = "#6C6260"

[colors.accents]
blue = "#6C6260"
green = "#404A60"
magenta = "#6A777F"
orange = "#385C66"
purple = "#6A777F"
red = "#464A49"
yellow = "#385C66"
cyan = "#959A9A"

[colors.list.item.selection]
background = { name = "#6C6260", opacity = 0.3 }
secondary_background = "#878989"
foreground = "#6C6260"

[colors.list.item.hover]
background = { name = "#6C6260", opacity = 0.15 }
