# Wallust generated Vicinae theme

[meta]
version = 1
name = "Wallust"
description = "Dynamic colors from wallpaper"
variant = "dark"

[colors.core]
background = "#130F10"
foreground = "#FAF0EB"
secondary_background = "#3B3839"
border = "#A79E98"
accent = "#CF7747"

[colors.accents]
blue = "#CF7747"
green = "#6F6C47"
magenta = "#938DB0"
orange = "#3F8A9B"
purple = "#938DB0"
red = "#814C4F"
yellow = "#3F8A9B"
cyan = "#F0D5C5"

[colors.list.item.selection]
background = { name = "#CF7747", opacity = 0.3 }
secondary_background = "#A79E98"
foreground = "#CF7747"

[colors.list.item.hover]
background = { name = "#CF7747", opacity = 0.15 }
