# Wallust generated Vicinae theme

[meta]
version = 1
name = "Wallust"
description = "Dynamic colors from wallpaper"
variant = "dark"

[colors.core]
background = "#1C211E"
foreground = "#EDEAE0"
secondary_background = "#424844"
border = "#9B988E"
accent = "#7098A5"

[colors.accents]
blue = "#7098A5"
green = "#6A654C"
magenta = "#FF8C01"
orange = "#B75844"
purple = "#FF8C01"
red = "#275577"
yellow = "#B75844"
cyan = "#CCC4A7"

[colors.list.item.selection]
background = { name = "#7098A5", opacity = 0.3 }
secondary_background = "#9B988E"
foreground = "#7098A5"

[colors.list.item.hover]
background = { name = "#7098A5", opacity = 0.15 }
