# Wallust generated Vicinae theme

[meta]
version = 1
name = "Wallust"
description = "Dynamic colors from wallpaper"
variant = "dark"

[colors.core]
background = "#191B19"
foreground = "#E8E8DB"
secondary_background = "#3F4240"
border = "#959589"
accent = "#728960"

[colors.accents]
blue = "#728960"
green = "#3B553B"
magenta = "#A2812D"
orange = "#625114"
purple = "#A2812D"
red = "#121D15"
yellow = "#625114"
cyan = "#BCBD99"

[colors.list.item.selection]
background = { name = "#728960", opacity = 0.3 }
secondary_background = "#959589"
foreground = "#728960"

[colors.list.item.hover]
background = { name = "#728960", opacity = 0.15 }
