# Wallust generated Vicinae theme

[meta]
version = 1
name = "Wallust"
description = "Dynamic colors from wallpaper"
variant = "dark"

[colors.core]
background = "#1F1B19"
foreground = "#FFE8CC"
secondary_background = "#47413F"
border = "#AC957A"
accent = "#62564D"

[colors.accents]
blue = "#62564D"
green = "#1F312E"
magenta = "#C17134"
orange = "#952D12"
purple = "#C17134"
red = "#2C160B"
yellow = "#952D12"
cyan = "#FEBC6E"

[colors.list.item.selection]
background = { name = "#62564D", opacity = 0.3 }
secondary_background = "#AC957A"
foreground = "#62564D"

[colors.list.item.hover]
background = { name = "#62564D", opacity = 0.15 }
