# Wallust generated Vicinae theme

[meta]
version = 1
name = "Wallust"
description = "Dynamic colors from wallpaper"
variant = "dark"

[colors.core]
background = "#312E2E"
foreground = "#FDF8E8"
secondary_background = "#555252"
border = "#ABA695"
accent = "#9D836A"

[colors.accents]
blue = "#9D836A"
green = "#973605"
magenta = "#78B498"
orange = "#516568"
purple = "#78B498"
red = "#392B2B"
yellow = "#516568"
cyan = "#FAEBBD"

[colors.list.item.selection]
background = { name = "#9D836A", opacity = 0.3 }
secondary_background = "#ABA695"
foreground = "#9D836A"

[colors.list.item.hover]
background = { name = "#9D836A", opacity = 0.15 }
