# Wallust generated Vicinae theme

[meta]
version = 1
name = "Wallust"
description = "Dynamic colors from wallpaper"
variant = "dark"

[colors.core]
background = "#000002"
foreground = "#DDE0E1"
secondary_background = "#000002"
border = "#8A8E8E"
accent = "#657187"

[colors.accents]
blue = "#657187"
green = "#613E28"
magenta = "#937A6A"
orange = "#5C5F38"
purple = "#937A6A"
red = "#2F343B"
yellow = "#5C5F38"
cyan = "#9DA7A8"

[colors.list.item.selection]
background = { name = "#657187", opacity = 0.3 }
secondary_background = "#8A8E8E"
foreground = "#657187"

[colors.list.item.hover]
background = { name = "#657187", opacity = 0.15 }
