# Wallust generated Vicinae theme

[meta]
version = 1
name = "Wallust"
description = "Dynamic colors from wallpaper"
variant = "dark"

[colors.core]
background = "#262A2B"
foreground = "#FDF4E4"
secondary_background = "#4B4F50"
border = "#AAA191"
accent = "#A78E8A"

[colors.accents]
blue = "#A78E8A"
green = "#546F4E"
magenta = "#93B4AD"
orange = "#017CA4"
purple = "#93B4AD"
red = "#734C31"
yellow = "#017CA4"
cyan = "#F9DFB1"

[colors.list.item.selection]
background = { name = "#A78E8A", opacity = 0.3 }
secondary_background = "#AAA191"
foreground = "#A78E8A"

[colors.list.item.hover]
background = { name = "#A78E8A", opacity = 0.15 }
