# Wallust generated Yazi theme

[mgr]
cwd = { fg = "#B9ADDF" }

[tabs]
active   = { fg = "#110011", bg = "#B9ADDF", bold = true }
inactive = { fg = "#B9ADDF", bg = "#ADA779" }

[mode]
normal_main = { fg = "#110011", bg = "#B9ADDF", bold = true }
normal_alt  = { fg = "#B9ADDF", bg = "#ADA779" }

[filetype]
rules = [
    # Folders - accent color
    { name = "*/", fg = "#B9ADDF" },
    # Image
    { mime = "image/*", fg = "#FFEE6D" },
    # Media
    { mime = "{audio,video}/*", fg = "#AD9882" },
    # Archive
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#16D0CF" },
    # Document
    { mime = "application/{pdf,doc,rtf}", fg = "#FA4D29" },
    # Fallback
    { name = "*", fg = "#FFF9CC" },
]
