# Wallust generated Yazi theme

[mgr]
cwd = { fg = "#7098A5" }

[tabs]
active   = { fg = "#424844", bg = "#7098A5", bold = true }
inactive = { fg = "#7098A5", bg = "#9B988E" }

[mode]
normal_main = { fg = "#424844", bg = "#7098A5", bold = true }
normal_alt  = { fg = "#7098A5", bg = "#9B988E" }

[filetype]
rules = [
    # Folders - accent color
    { name = "*/", fg = "#7098A5" },
    # Image
    { mime = "image/*", fg = "#CCC4A7" },
    # Media
    { mime = "{audio,video}/*", fg = "#B75844" },
    # Archive
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#FF8C01" },
    # Document
    { mime = "application/{pdf,doc,rtf}", fg = "#6A654C" },
    # Fallback
    { name = "*", fg = "#EDEAE0" },
]
