# Wallust generated Vicinae theme

[meta]
version = 1
name = "Wallust"
description = "Dynamic colors from wallpaper"
variant = "dark"

[colors.core]
background = "{{background}}"
foreground = "{{foreground}}"
secondary_background = "{{color0}}"
border = "{{color8}}"
accent = "{{color4}}"

[colors.accents]
blue = "{{color4}}"
green = "{{color2}}"
magenta = "{{color5}}"
orange = "{{color3}}"
purple = "{{color5}}"
red = "{{color1}}"
yellow = "{{color3}}"
cyan = "{{color6}}"

[colors.list.item.selection]
background = { name = "{{color4}}", opacity = 0.3 }
secondary_background = "{{color8}}"
foreground = "{{color4}}"

[colors.list.item.hover]
background = { name = "{{color4}}", opacity = 0.15 }
